// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCustomCountHandlerFunc turns a function with the right signature into a get custom count handler
type GetCustomCountHandlerFunc func(GetCustomCountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCustomCountHandlerFunc) Handle(params GetCustomCountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCustomCountHandler interface for that can handle valid get custom count params
type GetCustomCountHandler interface {
	Handle(GetCustomCountParams, interface{}) middleware.Responder
}

// NewGetCustomCount creates a new http.Handler for the get custom count operation
func NewGetCustomCount(ctx *middleware.Context, handler GetCustomCountHandler) *GetCustomCount {
	return &GetCustomCount{Context: ctx, Handler: handler}
}

/*GetCustomCount swagger:route GET /custom/{count} getCustomCount

Generate results based on a pattern/template.

*/
type GetCustomCount struct {
	Context *middleware.Context
	Handler GetCustomCountHandler
}

func (o *GetCustomCount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCustomCountParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
