// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Pseudo Service
Deterministic or pseudo-random data generator


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    License: AGPL 2.0
    Contact: https://github.com/bgadrian

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
