// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Deterministic or pseudo-random data generator",
    "title": "Pseudo Service",
    "contact": {
      "name": "https://github.com/bgadrian"
    },
    "license": {
      "name": "AGPL 2.0"
    },
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/health": {
      "get": {
        "description": "Get the health of the service",
        "responses": {
          "200": {
            "description": "Everything is fine"
          },
          "default": {
            "description": "Service is not available"
          }
        }
      }
    },
    "/users/{count}": {
      "get": {
        "security": [
          {
            "apikey": []
          }
        ],
        "description": "Get a random user",
        "parameters": [
          {
            "maximum": 500,
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "x-exportParamName": "Count",
            "description": "How many users to return",
            "name": "count",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "x-exportParamName": "Seed",
            "description": "Seed that will be used to generate the users (deterministic call). The seed will determine the first User data, seed+1 the next user, and so on. If no seed is provided a pseudo-random one will be generated (rand.Int63).",
            "name": "seed",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "The users were successfully generated",
            "schema": {
              "$ref": "#/definitions/ResponseModel"
            }
          },
          "default": {
            "description": "Error occurred",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorModel": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      },
      "example": {
        "code": 42,
        "message": "Something went wrong"
      }
    },
    "ResponseModel": {
      "type": "object",
      "properties": {
        "nextseed": {
          "description": "Use this to get the next users from the deterministic series",
          "type": "integer",
          "format": "int64"
        },
        "seed": {
          "description": "Number that was used to generate these users",
          "type": "integer",
          "format": "int64"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        }
      },
      "example": {
        "nextseed": 6,
        "seed": 0,
        "users": [
          {
            "age": 33,
            "company": "De-engineered niches Group",
            "country": "Romania",
            "email": "john@mambo.dot",
            "friends": [
              "3d813194-e9ed-4b09-a1ae-301b83bfdd9d",
              "356b1896-ee58-4fd8-931d-4cfaee21158e"
            ],
            "id": "356b1896-ee58-4fd8-931d-4cfaee21158e",
            "name": "John Doe",
            "position": "Central Branding Producer"
          }
        ]
      }
    },
    "User": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "Company": {
          "type": "string",
          "example": "De-engineered niches Group"
        },
        "age": {
          "type": "number",
          "format": "int32",
          "maximum": 255,
          "minimum": 0
        },
        "country": {
          "type": "string",
          "example": "Romania"
        },
        "email": {
          "type": "string",
          "example": "john@mambo.dot"
        },
        "friends": {
          "description": "Random list of UUIDs from the same response. To increase the chance of having friends request for bigger batches.",
          "type": "array",
          "items": {
            "description": "UUID for this friend",
            "type": "string",
            "example": "356b1896-ee58-4fd8-931d-4cfaee21158e"
          },
          "example": [
            "356b1896-ee58-4fd8-931d-4cfaee21158e",
            "3d813194-e9ed-4b09-a1ae-301b83bfdd9d"
          ]
        },
        "id": {
          "description": "UUID for this user",
          "type": "string",
          "format": "uuid",
          "example": "356b1896-ee58-4fd8-931d-4cfaee21158e"
        },
        "name": {
          "description": "First and Last name",
          "type": "string",
          "example": "John Doe"
        },
        "position": {
          "type": "string",
          "example": "Central Branding Producer"
        }
      },
      "example": {
        "age": 33,
        "company": "De-engineered niches Group",
        "country": "Romania",
        "email": "john@mambo.dot",
        "friends": [
          "3d813194-e9ed-4b09-a1ae-301b83bfdd9d",
          "356b1896-ee58-4fd8-931d-4cfaee21158e"
        ],
        "id": "356b1896-ee58-4fd8-931d-4cfaee21158e",
        "name": "John Doe",
        "position": "Central Branding Producer"
      }
    }
  },
  "securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "token",
      "in": "query"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Deterministic or pseudo-random data generator",
    "title": "Pseudo Service",
    "contact": {
      "name": "https://github.com/bgadrian"
    },
    "license": {
      "name": "AGPL 2.0"
    },
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/health": {
      "get": {
        "description": "Get the health of the service",
        "responses": {
          "200": {
            "description": "Everything is fine"
          },
          "default": {
            "description": "Service is not available"
          }
        }
      }
    },
    "/users/{count}": {
      "get": {
        "security": [
          {
            "apikey": []
          }
        ],
        "description": "Get a random user",
        "parameters": [
          {
            "maximum": 500,
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "x-exportParamName": "Count",
            "description": "How many users to return",
            "name": "count",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "x-exportParamName": "Seed",
            "description": "Seed that will be used to generate the users (deterministic call). The seed will determine the first User data, seed+1 the next user, and so on. If no seed is provided a pseudo-random one will be generated (rand.Int63).",
            "name": "seed",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "The users were successfully generated",
            "schema": {
              "$ref": "#/definitions/ResponseModel"
            }
          },
          "default": {
            "description": "Error occurred",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorModel": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      },
      "example": {
        "code": 42,
        "message": "Something went wrong"
      }
    },
    "ResponseModel": {
      "type": "object",
      "properties": {
        "nextseed": {
          "description": "Use this to get the next users from the deterministic series",
          "type": "integer",
          "format": "int64"
        },
        "seed": {
          "description": "Number that was used to generate these users",
          "type": "integer",
          "format": "int64"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        }
      },
      "example": {
        "nextseed": 6,
        "seed": 0,
        "users": [
          {
            "age": 33,
            "company": "De-engineered niches Group",
            "country": "Romania",
            "email": "john@mambo.dot",
            "friends": [
              "3d813194-e9ed-4b09-a1ae-301b83bfdd9d",
              "356b1896-ee58-4fd8-931d-4cfaee21158e"
            ],
            "id": "356b1896-ee58-4fd8-931d-4cfaee21158e",
            "name": "John Doe",
            "position": "Central Branding Producer"
          }
        ]
      }
    },
    "User": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "Company": {
          "type": "string",
          "example": "De-engineered niches Group"
        },
        "age": {
          "type": "number",
          "format": "int32",
          "maximum": 255,
          "minimum": 0
        },
        "country": {
          "type": "string",
          "example": "Romania"
        },
        "email": {
          "type": "string",
          "example": "john@mambo.dot"
        },
        "friends": {
          "description": "Random list of UUIDs from the same response. To increase the chance of having friends request for bigger batches.",
          "type": "array",
          "items": {
            "description": "UUID for this friend",
            "type": "string",
            "example": "356b1896-ee58-4fd8-931d-4cfaee21158e"
          },
          "example": [
            "356b1896-ee58-4fd8-931d-4cfaee21158e",
            "3d813194-e9ed-4b09-a1ae-301b83bfdd9d"
          ]
        },
        "id": {
          "description": "UUID for this user",
          "type": "string",
          "format": "uuid",
          "example": "356b1896-ee58-4fd8-931d-4cfaee21158e"
        },
        "name": {
          "description": "First and Last name",
          "type": "string",
          "example": "John Doe"
        },
        "position": {
          "type": "string",
          "example": "Central Branding Producer"
        }
      },
      "example": {
        "age": 33,
        "company": "De-engineered niches Group",
        "country": "Romania",
        "email": "john@mambo.dot",
        "friends": [
          "3d813194-e9ed-4b09-a1ae-301b83bfdd9d",
          "356b1896-ee58-4fd8-931d-4cfaee21158e"
        ],
        "id": "356b1896-ee58-4fd8-931d-4cfaee21158e",
        "name": "John Doe",
        "position": "Central Branding Producer"
      }
    }
  },
  "securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "token",
      "in": "query"
    }
  }
}`))
}
